# Core raw EDA

In [1]:
import sys
sys.path.insert(0, '/home/lu72hip/DIGICHer/dh_pipeline/src')

import pandas as pd
from pathlib import Path
from lib.database.duck.create_connection import create_duck_connection
from utils.config.config_loader import get_query_config

config = get_query_config()["core_v3"]
DB = Path(config['path_duck'])

con = create_duck_connection(str(DB))
con.execute("SET memory_limit='128GB'")
con.execute("SET threads=8")
print(f'Connected to {DB}')

pd.set_option("display.max_rows", 50) # Show more rows  # or None for unlimited
pd.set_option("display.max_columns", None) # Show more columns  # None = show all
pd.set_option("display.max_colwidth", None) # Don't truncate column content  # None = full content
pd.set_option("display.width", None) # Wider display  # Auto-detect terminal width

/home/lu72hip/DIGICHer/dh_pipeline/config/config_queries.json {'arxiv': {'checkpoint': 'submittedDateTo', 'queries': [{'query': '(all:cultural+OR+all:heritage+OR+all:digital+OR+all:humanities)', 'download_attachments': True, 'checkpoint_start': '1990-01-01-00-00', 'checkpoint_range': '6'}, {'query': 'all:computing+AND+(all:humanities+OR+all:heritage)', 'download_attachments': True, 'checkpoint_start': '1990-01-01-00-00', 'checkpoint_range': '6'}]}, 'cordis': {'checkpoint': 'startDate', 'queries': [{'query': 'cultural OR heritage OR digital OR humanities', 'download_attachments': True, 'checkpoint_start': '1985-01-01', 'checkpoint_range': '1'}, {'query': "contenttype='project' AND '*'", 'download_attachments': False, 'checkpoint_start': '1985-01-01', 'checkpoint_range': '1', 'path_duck': '/vast/lu72hip/data/duckdb/sources/cordis_raw.duckdb'}]}, 'coreac': {'checkpoint': 'publishedDate', 'queries': [{'query': '((computing AND cultural) OR (computing AND heritage))', 'download_attachments': False, 'checkpoint_start': '1990-01-01', 'checkpoint_range': '10'}]}, 'openaire': {'checkpoint': 'startYear', 'queries': [{'query': 'cultural', 'download_attachments': False, 'checkpoint_start': '1957', 'checkpoint_range': '1'}, {'query': 'heritage', 'download_attachments': False, 'checkpoint_start': '1957', 'checkpoint_range': '1'}, {'query': 'digital', 'download_attachments': False, 'checkpoint_start': '1957', 'checkpoint_range': '1'}, {'query': 'humanities', 'download_attachments': False, 'checkpoint_start': '1957', 'checkpoint_range': '1'}]}, 'meta_heritage': {'checkpoint': None}, 'openaire_dump': {'path_raw': '/vast/lu72hip/data/pile/openaire_2025_12_01_dump', 'path_duck': '/vast/lu72hip/data/duckdb/sources/openaire_raw.duckdb', 'path_duck_staging': '/vast/lu72hip/data/duckdb/sources/openaire_staging.duckdb'}, 'openalex_dump': {'path_raw': '/vast/lu72hip/data/pile/openalex_2026_02_03_dump', 'path_duck': '/vast/lu72hip/data/duckdb/sources/openalex_raw.duckdb'}, 'ror_dump': {'path_raw': '/vast/lu72hip/data/pile/ror_2026_02_24_dump/v2.3-2026-02-24-ror-data.json', 'path_duck': '/vast/lu72hip/data/duckdb/sources/ror_raw.duckdb'}, 'core_v3': {'path_duck': '/vast/lu72hip/data/duckdb/core/core_v3.duckdb'}}
Connected to /vast/lu72hip/data/duckdb/core/core_v3.duckdb

## Stats

In [2]:
q = """ 
SELECT
    table_name,
    estimated_size as cnt
FROM duckdb_tables()
WHERE schema_name = 'main'
ORDER BY estimated_size DESC
"""
con.execute(q).df()

       table_name        cnt
0        relation  562206510
1            work  205841448
2         project    3656773
3  relation_topic    3648111
4    organization     448161
5           topic       4516

## Projects and their Topics

In [3]:
q = """ 
SELECT *
FROM relation_topic
LIMIT 3
"""
con.execute(q).df()

      type      source_id  topic_id     score created_at
0  project  3722803268331     14316  0.170100        NaT
1  project  5977149805285     11295  0.226497        NaT
2  project   196473757163     14394  0.274071        NaT

In [6]:
q = """ 
SELECT p.title, t.topic_name
FROM project p 
LEFT JOIN relation_topic rt on rt.source_id = p.id
LEFT JOIN topic t on rt.topic_id = t.id
LIMIT 3
"""
con.execute(q).df()

,title,topic_name
0,"Dissertation Research: Evolution and Systematics of a Widespread Polyploid Fern Complex, Dryopteris filix-mas",Plant Ecology and Taxonomy Studies
1,Assimilation Efficiencies of Small Mammal Populations,Efficiency Analysis Using DEA
2,Development of Novel Augmented Reality Tool for Teaching Molecular Visualization in Biochemistry,Data Visualization and Analytics